
import React from 'react';
import type { Strategy } from '../types';
import { CheckCircleIcon } from './IconComponents';

interface StrategyDisplayProps {
  goal: string;
  strategies: Strategy[];
  onReset: () => void;
}

const getScoreColor = (score: number) => {
    if (score >= 0.9) return 'text-green-400';
    if (score >= 0.8) return 'text-yellow-400';
    return 'text-red-400';
};

const pathDetails = {
    Alpha: { emoji: '🚀', name: 'Alpha Path', borderColor: 'border-red-500/50' },
    Beta: { emoji: '📈', name: 'Beta Path', borderColor: 'border-blue-500/50' },
    Gamma: { emoji: '🛡️', name: 'Gamma Path', borderColor: 'border-green-500/50' },
};

const StrategyCard: React.FC<{ strategy: Strategy }> = ({ strategy }) => (
    <div className={`bg-brand-surface rounded-lg border ${pathDetails[strategy.path].borderColor} p-6 flex flex-col animate-slide-up`}>
        <div className="flex-grow">
            <div className="flex justify-between items-start mb-3">
                <div>
                    <h3 className="text-2xl font-bold text-brand-text">
                        <span className="mr-2">{pathDetails[strategy.path].emoji}</span>
                        {pathDetails[strategy.path].name}
                    </h3>
                    <p className="text-brand-primary font-semibold">{strategy.title}</p>
                </div>
                {strategy.ethicalScore && (
                     <div className={`text-sm font-bold flex items-center gap-1 ${getScoreColor(strategy.ethicalScore.score)}`}>
                        P(G): {strategy.ethicalScore.score.toFixed(2)}
                    </div>
                )}
            </div>
            <p className="text-brand-subtle text-sm mb-4">{strategy.description}</p>
            {strategy.ethicalScore && (
                 <p className="text-xs italic text-brand-subtle mb-5 p-2 bg-brand-bg rounded-md border border-brand-subtle/10">
                    <span className="font-bold">Ethical Rationale:</span> {strategy.ethicalScore.rationale}
                </p>
            )}

            <h4 className="font-semibold text-brand-text mb-3">Actionable Steps:</h4>
            <ul className="space-y-3">
                {strategy.steps.map((step, index) => (
                    <li key={index} className="flex items-start text-sm">
                        <CheckCircleIcon className="w-5 h-5 text-brand-primary mr-3 flex-shrink-0 mt-0.5" />
                        <span className="text-brand-text">{step}</span>
                    </li>
                ))}
            </ul>
        </div>
    </div>
);


export const StrategyDisplay: React.FC<StrategyDisplayProps> = ({ goal, strategies, onReset }) => {
    return (
        <div className="w-full animate-fade-in">
             <div className="text-center mb-10">
                <h2 className="text-3xl sm:text-4xl font-bold text-brand-text">Optimized Strategic Paths</h2>
                <p className="text-brand-subtle mt-2 max-w-3xl mx-auto">
                    Based on your goal <span className="text-brand-text font-semibold">"{goal}"</span>, here are three distinct strategies generated by the Cognitive Optimization framework.
                </p>
            </div>
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                {strategies.sort((a,b) => a.path.localeCompare(b.path)).map((strategy, index) => (
                    <StrategyCard key={index} strategy={strategy} />
                ))}
            </div>
        </div>
    );
};
